language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.8
  - DJANGO_VERSION=1.5.4
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -r testproject/requirements_test.txt
  - python setup.py install
script:
  - cd testproject
  - python manage.py test testapp
  - coverage run --source=django_pony_forms,testapp manage.py test testapp
  - coverage report -m
before_install:
  - pip install pep8
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
after_success:
  - pip install -r requirements_coveralls.txt
  - coveralls
  - pip install coviolations_app
  - covio
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.3.7
    - python: 3.3
      env: DJANGO_VERSION=1.4.8