language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -r testproject/requirements_jenkins.txt
  - python setup.py install
script:
  - cd testproject
  - mkdir -p reports
  - python manage.py jenkins
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.3.7
    - python: 3.3
      env: DJANGO_VERSION=1.4.5